# Generated by Django 5.0.9 on 2024-12-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ordem_servico', '0003_contato_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='grupos_liberados',
            field=models.ManyToManyField(blank=True, related_name='chamados_liberados', to='auth.group'),
        ),
    ]
