# Generated by Django 5.0.9 on 2025-02-05 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0004_chamado_grupos_liberados'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='chamado',
            name='grupo_trabalho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordem_servico.grupotrabalho'),
        ),
    ]
