# Generated by Django 5.0.9 on 2025-01-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listacanais',
            name='data_criacao',
            field=models.DateField(),
        ),
    ]
