# Generated by Django 5.0.9 on 2025-01-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canais', '0002_alter_listacanais_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
