version: '3'

services:
  web:
    build: .
    container_name: meu_django
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./db_sistema.sqlite3:/app/db/db_sistema.sqlite3
    environment:
      DEBUG: "True"
      SECRET_KEY: "django-insecure-kux5c0$f*zz+y5e6_d73$mmn8ha+^$6#u+cotz62f%0t!mg-y0"
