# Generated by Django 5.0.9 on 2025-01-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_senhas', '0003_alter_senha_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='senha',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
