# Generated by Django 5.0.9 on 2025-06-26 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMassagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('duracao_minutos', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_hospede', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('numero_quarto', models.CharField(blank=True, max_length=10)),
                ('numero_reserva', models.CharField(blank=True, max_length=20)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('observacoes', models.TextField(blank=True)),
                ('primeira_vez', models.BooleanField(default=False)),
                ('tipo_massagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spa.tipomassagem')),
            ],
        ),
    ]
