# Generated by Django 5.0.9 on 2025-06-26 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['data', 'horario'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='horario',
            field=models.TimeField(verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='nome_hospede',
            field=models.CharField(max_length=100, verbose_name='Nome do Hóspede'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='numero_quarto',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número do Quarto'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='numero_reserva',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número da Reserva'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Informe sobre alergias, preferências de pressão, etc.', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='primeira_vez',
            field=models.BooleanField(choices=[(True, 'Primeira vez'), (False, 'Cliente retornando')], default=True, verbose_name='É sua primeira vez no spa?'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipo_massagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spa.tipomassagem', verbose_name='Tipo de Massagem'),
        ),
    ]
