# Generated by Django 5.0.9 on 2025-06-26 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0002_alter_agendamento_options_alter_agendamento_horario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['data', 'horario'], 'permissions': [('cancelar_agendamento', 'Pode cancelar agendamentos'), ('confirmar_agendamento', 'Pode confirmar agendamentos'), ('registrar_realizacao', 'Pode registrar realização de serviço')], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='tipomassagem',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo de Massagem', 'verbose_name_plural': 'Tipos de Massagem'},
        ),
        migrations.AddField(
            model_name='agendamento',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Cancelamento'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_realizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Realização'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='duracao',
            field=models.PositiveIntegerField(default=60, verbose_name='Duração (minutos)'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, verbose_name='Motivo do Cancelamento'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('realizado', 'Realizado'), ('nao_compareceu', 'Não Compareceu'), ('em_andamento', 'Em Andamento')], default='agendado', max_length=15),
        ),
        migrations.AddField(
            model_name='tipomassagem',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Desmarque para inativar temporariamente esta massagem', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
    ]
