# Generated by Django 5.0.9 on 2025-07-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0003_alter_agendamento_options_alter_tipomassagem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='primeira_vez',
            field=models.BooleanField(choices=[(True, 'Primeira vez'), (False, 'Cliente retornando')], default=True, verbose_name='Primeira vez no spa?'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('realizado', 'Realizado'), ('em_andamento', 'Em Andamento')], default='agendado', max_length=15),
        ),
    ]
