# Generated by Django 5.0.9 on 2025-07-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0004_alter_agendamento_primeira_vez_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='duracao',
        ),
    ]
