# Generated by Django 5.0.9 on 2024-12-18 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ramal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ramal', models.CharField(max_length=10, unique=True)),
                ('linha_completa', models.CharField(max_length=20)),
                ('atendente', models.CharField(max_length=100)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ramais', to='auth.group')),
            ],
        ),
    ]
