# Generated by Django 5.0.9 on 2024-12-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramal',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
