# Generated by Django 5.0.9 on 2026-02-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramais', '0002_ramal_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramal',
            name='instrucoes_pdf',
            field=models.TextField(blank=True, help_text='Instruções como: como fazer ligação, puxar ligação, etc.', verbose_name='Instruções para rodapé do PDF'),
        ),
    ]
