# Generated by Django 5.0.9 on 2026-02-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramais', '0003_ramal_instrucoes_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrucoesPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, verbose_name='Instruções para rodapé do PDF')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
