# Generated by Django 5.0.9 on 2025-02-14 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(help_text='Informe o CNPJ ou CPF (somente números)', max_length=14, unique=True, verbose_name='CNPJ/CPF')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('telefone', models.CharField(help_text='Informe o telefone com DDD (ex: 45999999999)', max_length=20, validators=[django.core.validators.RegexValidator(message='Formato inválido de telefone', regex='^\\+?\\d{8,15}$')], verbose_name='Telefone')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='E-mail')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_assinatura', models.DateField(verbose_name='Data de Assinatura')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor do Contrato')),
            ],
        ),
    ]
