# Generated by Django 5.0.9 on 2025-02-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se o contrato está ativo ou inativo.', verbose_name='Ativo'),
        ),
    ]
