# Generated by Django 5.0.9 on 2025-02-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_contrato_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='email_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
