# Generated by Django 5.0.9 on 2025-02-20 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contratos', '0003_contrato_email_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='grupo_responsavel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
    ]
