# Generated by Django 5.0.9 on 2025-02-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_contrato_grupo_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='email',
            field=models.EmailField(blank=True, max_length=50, unique=True, verbose_name='E-mail'),
        ),
    ]
