# Generated by Django 5.0.9 on 2025-02-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_alter_contrato_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='E-mail'),
        ),
    ]
