# Generated by Django 5.0.9 on 2025-02-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_alter_contrato_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='documento',
            field=models.CharField(help_text='Informe o CNPJ ou CPF (somente números)', max_length=14, verbose_name='CNPJ/CPF'),
        ),
    ]
