# Generated by Django 5.0.9 on 2025-05-08 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_alter_contrato_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='documento',
            field=models.CharField(help_text='Informe o CNPJ ou CPF (somente números)', max_length=14, validators=[django.core.validators.RegexValidator(message='O campo deve conter apenas números.', regex='^\\d+$')], verbose_name='CNPJ/CPF'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='telefone',
            field=models.CharField(blank=True, help_text='Informe o telefone com DDD (ex: 45999999999)', max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
