# Generated by Django 5.0.9 on 2025-07-14 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_alter_contrato_documento_alter_contrato_telefone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='grupo_responsavel',
        ),
        migrations.AddField(
            model_name='contrato',
            name='usuario_responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
            preserve_default=False,
        ),
    ]
