# Generated by Django 5.0.9 on 2025-07-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_remove_contrato_grupo_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='arquivo_contrato',
            field=models.FileField(blank=True, help_text='Faça o upload do arquivo do contrato (PDF, DOCX, JPG, etc.). Tamanho máximo: 20MB.', null=True, upload_to='contratos_arquivos/', verbose_name='Arquivo do Contrato'),
        ),
    ]
