# Generated by Django 5.0.9 on 2025-02-11 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLavanderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pesokg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valormedio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioLav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adata', models.DateTimeField(unique=True)),
                ('vrTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pesoTotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRelLavanderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_itens', models.IntegerField()),
                ('item_lavanderia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='governanca.itemlavanderia')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='governanca.relatoriolav')),
            ],
            options={
                'unique_together': {('relatorio', 'item_lavanderia')},
            },
        ),
    ]
