# Generated by Django 5.0.9 on 2025-02-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrellavanderia',
            name='qtd_relavagens',
            field=models.IntegerField(default=0),
        ),
    ]
