# Generated by Django 5.0.9 on 2025-02-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanca', '0002_itemrellavanderia_qtd_relavagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrellavanderia',
            name='pesokg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='itemrellavanderia',
            name='valormedio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
