# Generated by Django 5.0.9 on 2025-02-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanca', '0003_itemrellavanderia_pesokg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrellavanderia',
            name='relavagemkg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
