# Generated by Django 5.0.9 on 2025-02-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanca', '0004_itemrellavanderia_relavagemkg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriolav',
            name='adata',
            field=models.DateTimeField(),
        ),
    ]
