# Generated by Django 5.0.9 on 2025-02-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanca', '0005_alter_relatoriolav_adata'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrellavanderia',
            name='porcentagem_peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
