# Generated by Django 5.0.9 on 2025-12-05 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanca', '0006_itemrellavanderia_porcentagem_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ControleQuartos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('permanece_entrada', models.IntegerField(default=0, verbose_name='Meta de Entradas')),
                ('saida_entrada', models.IntegerField(default=0, verbose_name='Meta de Saídas')),
                ('quantidade_quartos', models.IntegerField(verbose_name='Quantidade Total de Quartos')),
                ('reservas_realizadas', models.IntegerField(default=0, verbose_name='Reservas Realizadas')),
                ('permanece_realizadas', models.IntegerField(default=0, verbose_name='Entradas Realizadas')),
                ('saidas_realizadas', models.IntegerField(default=0, verbose_name='Saídas Realizadas')),
                ('realizados', models.IntegerField(default=0, verbose_name='Total Realizados')),
                ('porcentagem', models.FloatField(default=0.0, verbose_name='Porcentagem (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='governanca.funcionarios', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Controle de Quartos',
                'verbose_name_plural': 'Controle de Quartos',
                'ordering': ['-data', 'funcionario__nome'],
                'unique_together': {('data', 'funcionario')},
            },
        ),
    ]
