# Generated by Django 5.0.9 on 2025-12-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governanca', '0007_funcionarios_controlequartos'),
    ]

    operations = [
    ]
