# Generated by Django 5.0.9 on 2025-12-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanca', '0008_auto_20251205_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlequartos',
            name='permanece_entrada',
            field=models.IntegerField(default=0, verbose_name='Meta de Quartos que Permanecem'),
        ),
        migrations.AlterField(
            model_name='controlequartos',
            name='quantidade_quartos',
            field=models.IntegerField(default=16, verbose_name='Quantidade Total de Quartos'),
        ),
        migrations.AlterField(
            model_name='controlequartos',
            name='reservas_realizadas',
            field=models.IntegerField(default=0, help_text='Quartos de saída com limpeza especial (já incluído no total de saídas)', verbose_name='Reservas Realizadas'),
        ),
        migrations.AlterField(
            model_name='controlequartos',
            name='saida_entrada',
            field=models.IntegerField(default=0, verbose_name='Meta de Quartos de Saída'),
        ),
    ]
