# Generated by Django 5.0.9 on 2025-12-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanca', '0009_alter_controlequartos_permanece_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlequartos',
            name='reservas_realizadas',
            field=models.IntegerField(default=0, help_text='Quartos de saída do tipo reserva (já incluído no total de saídas)', verbose_name='Reservas Realizadas'),
        ),
    ]
