# Generated by Django 5.0.9 on 2025-12-06 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanca', '0010_alter_controlequartos_reservas_realizadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Motivo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('cor', models.CharField(default='#dc3545', help_text='Cor para identificação visual (ex: #FF0000)', max_length=7, verbose_name='Cor (Hex)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Motivo de Ausência',
                'verbose_name_plural': 'Motivos de Ausência',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='controlequartos',
            options={'ordering': ['-data', 'funcionario__nome'], 'verbose_name': 'Controle de Quartos', 'verbose_name_plural': 'Controles de Quartos'},
        ),
        migrations.AddField(
            model_name='controlequartos',
            name='motivo_ausencia',
            field=models.ForeignKey(blank=True, help_text='Se preenchido, este dia não contará para as metas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='governanca.motivoausencia', verbose_name='Motivo de Ausência'),
        ),
    ]
