# Generated by Django 5.0.9 on 2025-12-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governanca', '0011_motivoausencia_alter_controlequartos_options_and_more'),
    ]

    operations = [
    ]
