# Generated by Django 5.0.9 on 2025-12-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanca', '0012_adicionar_motivo_ausencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivoausencia',
            name='afeta_media',
            field=models.BooleanField(default=False, help_text='Se marcado, este motivo será contado negativamente nas estatísticas', verbose_name='Afeta Média de Performance'),
        ),
        migrations.AddField(
            model_name='motivoausencia',
            name='sistema',
            field=models.BooleanField(default=False, help_text='Motivos do sistema não podem ser editados ou excluídos', verbose_name='Motivo do Sistema'),
        ),
    ]
